### ISSUE TITLE
create-realm api in dataset module throws an java.lang.NoSuchMethodError when run against KC 17.0.0-SNAPSHOT/KC 16.1.0/KC 16.0.0

### ISSUE THREAD

**Issue by kami619** [keycloak/keycloak-benchmark#34]
### Describe the bug

create-realm api in dataset module throws an java.lang.NoSuchMethodError on org.jboss.resteasy.spi.HttpRequest.getUri() method when the keycloak-benchmark-0.7 version is run against the latest of the keycloak-server with 17.0.0-SNAPSHOT version.

The issue seems to persist even with the 16.1.0 and 16.0.0 release versions of keycloak-server mentioned in the [pom](https://github.com/keycloak/keycloak-benchmark/blob/main/pom.xml#L13) of keycloak-benchmark project.

The last known working version matrix seems to be

> keycloak-server 16.0.0-SNAPSHOT (not the release version) + keycloak-benchmark 0.7
> keycloak-server 15 + keycloak-benchmark 0.6

### Version

17.0.0-SNAPSHOT, 16.1.0, 16.0.0

### Expected behavior

We expect the create realms api to work without issue when we use keycloak-server  version :  17.0.0-SNAPSHOT or 16.1.0 and keycloak-benchmark version : 0.7

### Actual behavior

`curl http://localhost:8080/auth/realms/master/dataset/create-realms?count=2`

when the above rest endpoint is called, we are getting an exception with the below stack trace

```
11:46:16,550 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-1) Uncaught server error: java.lang.NoSuchMethodError: org.jboss.resteasy.spi.HttpRequest.getUri()Lorg/jboss/resteasy/spi/ResteasyUriInfo; 
at org.keycloak.benchmark.dataset.config.ConfigUtil.createConfigFromQueryParams(ConfigUtil.java:54)
at org.keycloak.benchmark.dataset.DatasetResourceProvider.createRealms(DatasetResourceProvider.java:112)

 ```

### How to Reproduce?

Deploy the keycloak-benchmark 0.7 version module to a keycloak-server with the versions (17.0.0-SNAPSHOT or 16.1.0 or 16.0.0) following the documentation provided in the project [README](https://github.com/keycloak/keycloak-benchmark/blob/main/README.md)

And execute the below rest endpoint

`curl http://localhost:8080/auth/realms/master/dataset/create-realms?count=2`

note: we sanity tested the build's for deployment issues with the status endpoint and that runs without issue in all matrix combinations of the keycloak-benchmark and keycloak-server which has issues with the create-realm api

```
$ curl http://localhost:8080/auth/realms/master/dataset/status | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    57  100    57    0     0    385      0 --:--:-- --:--:-- --:--:--   385
{
  "status": "No task in progress. New task can be started"
}
```

### Anything else?

Additional investigation notes provided by @tkyjovsk (Tomas K.)

the NoSuchMethodError for the getUri() method appeared in KC 16.0.0 release. in KC 16.0.0-SNAPSHOT built on 2021-12-06 didn't yet have the issue

**Comment by pedroigor** [comment]
Thanks. I think I have fixed some issues related to this. I'm going to review and provide a fix.

**Comment by kostiapl** [comment]
I have the same issue with KC 16.1.0. As a workaround, the DB can be seeded with KC 15.1.0 first, with the following switch to 16.1.0 with the same DB.

**Comment by ioemat** [comment]
The problem is, that there are different versions of resteasy are used within keycloak. The version references in the dependencies of keycloak-services.jar differs from the one that is available at runtime in quarkus and wildfly.
I provided a PR to fix that here

**Comment by kami619** [comment]
tested the https://github.com/keycloak/keycloak-benchmark/pull/36 works fine for KC-16.0.0 and KC-17.0.0-SNAPSHOT

**Comment by knopka** [comment]
Just tried with Keycloak 16.0.0 and still doesn't work for me. In logs see errors

```
ESC[0mESC[31m06:41:50,307 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-2) Uncaught server error: java.lang.NoSuchMethodError: 'org.jboss.resteasy.spi.ResteasyUriInfo org.jboss.resteasy.spi.
HttpRequest.getUri()'
        at deployment.keycloak-benchmark-dataset-0.6.jar//org.keycloak.benchmark.dataset.config.ConfigUtil.createConfigFromQueryParams(ConfigUtil.java:54)
        at deployment.keycloak-benchmark-dataset-0.6.jar//org.keycloak.benchmark.dataset.DatasetResourceProvider.createRealms(DatasetResourceProvider.java:113)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```
